### ISSUE TITLE
Add tags for local info

### ISSUE THREAD

**Issue by mmcghee18** [mmcghee18/qualityco#16]
Next to '$$' tags, add 'Made in [state]' tags (just 'made in', not 'designed in')

**Comment by skyetalavera** [comment]
@mmcghee18 I talked to my brother, and let's actually just do the 'Made in [state OR country] tag' next to the 'SS' tag

He thinks made in is more important. We'll pull it from the manufactured in column so it will sometimes be a list of states, and sometimes be a list of countries. We'll show states for those made in the USA and countries for anything outside of the US. If we know it's made in USA but not what state, I'll have John just put USA as the tag.
