### ISSUE TITLE
Filters should be "AND/OR" booleans, not "AND"

### ISSUE THREAD

**Issue by skyetalavera** [mmcghee18/qualityco#19]
Steps to Reproduce:
1. Search "Toothbrush"
2. Filter by Planet > Check the boxes for "Eco-friendly" (Terra & Co) and "environmentally friendly" (quip)
3. Get error message that nothing matched that search

Definition of Done
1. Search "Toothbrush"
2. Filter by Planet > Check the boxes for "Eco-friendly" (Terra & Co) and "environmentally friendly" (quip)
3. Both Terra & Co and quip show up as results. 

<img width="817" alt="Screen Shot 2020-08-26 at 9 25 08 AM" src="https://user-images.githubusercontent.com/69161425/91331042-1d7fd080-e77f-11ea-863b-0111d136b82c.png">

Basically when you select a tag, it shows all the results that match that tag. So rather than reducing down, the more tags you select, the more results you see. I realize this is not quite filtering, but I think it makes more sense for the consumer, right? They might want to see anything that is either eco-friendly or woman-founded. Since we probably won't have more than 10 brands listed per search, I'm thinking this makes more sense, but I'd love your perspective too.

For instance, when you search for a shirt on Nordstrom, you can select which color items you want. If you select white, cream, and beige, it will show you any item in that color, not just the items that contain all three colors.

<img width="1276" alt="Screen Shot 2020-08-26 at 9 30 54 AM" src="https://user-images.githubusercontent.com/69161425/91330957-fe813e80-e77e-11ea-9195-cd10b9d53e36.png">

**Comment by skyetalavera** [comment]
Would be the same as the way the Price filter works right now.

Would also want this new logic to be applied to the Local filter too.

**Comment by mmcghee18** [comment]
Since we're not sure which is best, I'm going to add a switch here where you can choose whether you're in AND or OR mode
