### ISSUE TITLE
Change local dropdown to show "Made in" and "Designed in"

### ISSUE THREAD

**Issue by skyetalavera** [mmcghee18/qualityco#22]
On Local filter button

Change "Designed" to "Designed in"
Change "Manufactured" to "Made in"
Delete Company HQ
Delete Warehoused

I want it to be a bit more streamlined and less confusing. We'll keep sourcing this data in airtable just in case, but for now I don't want it displaying to the user

**Comment by mmcghee18** [comment]
Done
