### ISSUE TITLE
Create a table for Places

### ISSUE THREAD

**Issue by mmcghee18** [mmcghee18/qualityco#31]
All possible Places should be stored in a table so I can show an accurate menu of options to filter from

**Comment by skyetalavera** [comment]
@mmcghee18 Can we also have a column for countries in this table?

And then when you filter by location, you can add both states and countries into the search bar? I could especially see someone wanting to search by Made in the USA vs a bunch of individual states.

<img width="973" alt="Screen Shot 2020-09-03 at 10 13 57 AM" src="https://user-images.githubusercontent.com/69161425/92146365-7201fc00-edce-11ea-977d-7f81292d20da.png">
