### ISSUE TITLE
Make buttons un-highlight when clicked

### ISSUE THREAD

**Issue by skyetalavera** [mmcghee18/qualityco#42]
Steps to Reproduce:
1. Click "Planet" button to select all of those tags
2. Planet button highlights orange
3. Click Planet button to deselect all tags
4. Planet button stays orange

Definition of Done
Planet button unhighlights when clicked a second time and no checkboxes are marked for that section

<img width="467" alt="Screen Shot 2020-09-09 at 8 20 02 AM" src="https://user-images.githubusercontent.com/69161425/92618848-a31e7880-f275-11ea-82d3-fe62eca750ad.png">

**Comment by mmcghee18** [comment]
Giving up 😭
