### ISSUE TITLE
Planet button menu flips up

### ISSUE THREAD

**Issue by skyetalavera** [mmcghee18/qualityco#43]
This may be a result of how many planet tags we have or my 13-inch macbook screen, but sometimes when I move my cursor over the "Planet" button, the menu shows above and not below:

<img width="1257" alt="Screen Shot 2020-09-09 at 8 17 41 AM" src="https://user-images.githubusercontent.com/69161425/92619024-db25bb80-f275-11ea-84ed-f758c993667e.png">

If this is hard to resolve, no worries. I plan on reducing the number of planet tags anyways, so it should be okay if it's hard to fix.

**Comment by mmcghee18** [comment]
Yeah, I think it's because of how many tags there are. It only happens every once and a while and there's not an easy way to fix it :(
